parameters:
    # path from project root
    epfremmer.swagger.file: swagger.yaml

    # service classes
    epfremmer.provider.swagger.class: Epfremmer\SwaggerBundle\Provider\SwaggerProvider
    epfremmer.serializer_subscriber.class: Epfremmer\SwaggerBundle\Listener\SerializationSubscriber

services:

    epfremmer.provider.swagger:
        class: %epfremmer.provider.swagger.class%
        arguments:
          - @kernel
          - @jms_serializer
          - %epfremmer.swagger.file%

    epfremmer.serializer.subscriber:
        class: %epfremmer.serializer_subscriber.class%
        tags:
            - { name: jms_serializer.event_subscriber }